language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer --verbose self-update
  - composer --version

install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - ln -s $TRAVIS_BUILD_DIR /tmp/repository
  - git clone https://github.com/drupal-composer/drupal-project.git /tmp/workspace
  - cp .travis.composer.json /tmp/workspace/composer.json
  - cd /tmp/workspace
  - composer require --verbose --prefer-dist drupal/name dev-8.x-1.x#$TRAVIS_COMMIT

script:
  - cd /tmp/workspace/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
